# Autogenerated from a Treetop grammar. Edits may be lost.


require "hemingway/symbol/symbol_nodes"

module Hemingway
  module Symbol
    include Treetop::Runtime

    def root
      @root ||= :math_symbol
    end

    def _nt_math_symbol
      start_index = index
      if node_cache[:math_symbol].has_key?(index)
        cached = node_cache[:math_symbol][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0 = index
      if has_terminal?("\\Gamma", false, index)
        r1 = instantiate_node(SyntaxNode,input, index...(index + 6))
        @index += 6
      else
        terminal_parse_failure("\\Gamma")
        r1 = nil
      end
      if r1
        r0 = r1
        r0.extend(SymbolNode)
      else
        if has_terminal?("\\Delta", false, index)
          r2 = instantiate_node(SyntaxNode,input, index...(index + 6))
          @index += 6
        else
          terminal_parse_failure("\\Delta")
          r2 = nil
        end
        if r2
          r0 = r2
          r0.extend(SymbolNode)
        else
          if has_terminal?("\\Theta", false, index)
            r3 = instantiate_node(SyntaxNode,input, index...(index + 6))
            @index += 6
          else
            terminal_parse_failure("\\Theta")
            r3 = nil
          end
          if r3
            r0 = r3
            r0.extend(SymbolNode)
          else
            if has_terminal?("\\Lambda", false, index)
              r4 = instantiate_node(SyntaxNode,input, index...(index + 7))
              @index += 7
            else
              terminal_parse_failure("\\Lambda")
              r4 = nil
            end
            if r4
              r0 = r4
              r0.extend(SymbolNode)
            else
              if has_terminal?("\\Xi", false, index)
                r5 = instantiate_node(SyntaxNode,input, index...(index + 3))
                @index += 3
              else
                terminal_parse_failure("\\Xi")
                r5 = nil
              end
              if r5
                r0 = r5
                r0.extend(SymbolNode)
              else
                if has_terminal?("\\Pi", false, index)
                  r6 = instantiate_node(SyntaxNode,input, index...(index + 3))
                  @index += 3
                else
                  terminal_parse_failure("\\Pi")
                  r6 = nil
                end
                if r6
                  r0 = r6
                  r0.extend(SymbolNode)
                else
                  if has_terminal?("\\Sigma", false, index)
                    r7 = instantiate_node(SyntaxNode,input, index...(index + 6))
                    @index += 6
                  else
                    terminal_parse_failure("\\Sigma")
                    r7 = nil
                  end
                  if r7
                    r0 = r7
                    r0.extend(SymbolNode)
                  else
                    if has_terminal?("\\Upsilon", false, index)
                      r8 = instantiate_node(SyntaxNode,input, index...(index + 8))
                      @index += 8
                    else
                      terminal_parse_failure("\\Upsilon")
                      r8 = nil
                    end
                    if r8
                      r0 = r8
                      r0.extend(SymbolNode)
                    else
                      if has_terminal?("\\Phi", false, index)
                        r9 = instantiate_node(SyntaxNode,input, index...(index + 4))
                        @index += 4
                      else
                        terminal_parse_failure("\\Phi")
                        r9 = nil
                      end
                      if r9
                        r0 = r9
                        r0.extend(SymbolNode)
                      else
                        if has_terminal?("\\Psi", false, index)
                          r10 = instantiate_node(SyntaxNode,input, index...(index + 4))
                          @index += 4
                        else
                          terminal_parse_failure("\\Psi")
                          r10 = nil
                        end
                        if r10
                          r0 = r10
                          r0.extend(SymbolNode)
                        else
                          if has_terminal?("\\Omega", false, index)
                            r11 = instantiate_node(SyntaxNode,input, index...(index + 6))
                            @index += 6
                          else
                            terminal_parse_failure("\\Omega")
                            r11 = nil
                          end
                          if r11
                            r0 = r11
                            r0.extend(SymbolNode)
                          else
                            if has_terminal?("\\alpha", false, index)
                              r12 = instantiate_node(SyntaxNode,input, index...(index + 6))
                              @index += 6
                            else
                              terminal_parse_failure("\\alpha")
                              r12 = nil
                            end
                            if r12
                              r0 = r12
                              r0.extend(SymbolNode)
                            else
                              if has_terminal?("\\beta", false, index)
                                r13 = instantiate_node(SyntaxNode,input, index...(index + 5))
                                @index += 5
                              else
                                terminal_parse_failure("\\beta")
                                r13 = nil
                              end
                              if r13
                                r0 = r13
                                r0.extend(SymbolNode)
                              else
                                if has_terminal?("\\gamma", false, index)
                                  r14 = instantiate_node(SyntaxNode,input, index...(index + 6))
                                  @index += 6
                                else
                                  terminal_parse_failure("\\gamma")
                                  r14 = nil
                                end
                                if r14
                                  r0 = r14
                                  r0.extend(SymbolNode)
                                else
                                  if has_terminal?("\\delta", false, index)
                                    r15 = instantiate_node(SyntaxNode,input, index...(index + 6))
                                    @index += 6
                                  else
                                    terminal_parse_failure("\\delta")
                                    r15 = nil
                                  end
                                  if r15
                                    r0 = r15
                                    r0.extend(SymbolNode)
                                  else
                                    if has_terminal?("\\epsilon", false, index)
                                      r16 = instantiate_node(SyntaxNode,input, index...(index + 8))
                                      @index += 8
                                    else
                                      terminal_parse_failure("\\epsilon")
                                      r16 = nil
                                    end
                                    if r16
                                      r0 = r16
                                      r0.extend(SymbolNode)
                                    else
                                      if has_terminal?("\\zeta", false, index)
                                        r17 = instantiate_node(SyntaxNode,input, index...(index + 5))
                                        @index += 5
                                      else
                                        terminal_parse_failure("\\zeta")
                                        r17 = nil
                                      end
                                      if r17
                                        r0 = r17
                                        r0.extend(SymbolNode)
                                      else
                                        if has_terminal?("\\eta", false, index)
                                          r18 = instantiate_node(SyntaxNode,input, index...(index + 4))
                                          @index += 4
                                        else
                                          terminal_parse_failure("\\eta")
                                          r18 = nil
                                        end
                                        if r18
                                          r0 = r18
                                          r0.extend(SymbolNode)
                                        else
                                          if has_terminal?("\\theta", false, index)
                                            r19 = instantiate_node(SyntaxNode,input, index...(index + 6))
                                            @index += 6
                                          else
                                            terminal_parse_failure("\\theta")
                                            r19 = nil
                                          end
                                          if r19
                                            r0 = r19
                                            r0.extend(SymbolNode)
                                          else
                                            if has_terminal?("\\iota", false, index)
                                              r20 = instantiate_node(SyntaxNode,input, index...(index + 5))
                                              @index += 5
                                            else
                                              terminal_parse_failure("\\iota")
                                              r20 = nil
                                            end
                                            if r20
                                              r0 = r20
                                              r0.extend(SymbolNode)
                                            else
                                              if has_terminal?("\\kappa", false, index)
                                                r21 = instantiate_node(SyntaxNode,input, index...(index + 6))
                                                @index += 6
                                              else
                                                terminal_parse_failure("\\kappa")
                                                r21 = nil
                                              end
                                              if r21
                                                r0 = r21
                                                r0.extend(SymbolNode)
                                              else
                                                if has_terminal?("\\lambda", false, index)
                                                  r22 = instantiate_node(SyntaxNode,input, index...(index + 7))
                                                  @index += 7
                                                else
                                                  terminal_parse_failure("\\lambda")
                                                  r22 = nil
                                                end
                                                if r22
                                                  r0 = r22
                                                  r0.extend(SymbolNode)
                                                else
                                                  if has_terminal?("\\mu", false, index)
                                                    r23 = instantiate_node(SyntaxNode,input, index...(index + 3))
                                                    @index += 3
                                                  else
                                                    terminal_parse_failure("\\mu")
                                                    r23 = nil
                                                  end
                                                  if r23
                                                    r0 = r23
                                                    r0.extend(SymbolNode)
                                                  else
                                                    if has_terminal?("\\nu", false, index)
                                                      r24 = instantiate_node(SyntaxNode,input, index...(index + 3))
                                                      @index += 3
                                                    else
                                                      terminal_parse_failure("\\nu")
                                                      r24 = nil
                                                    end
                                                    if r24
                                                      r0 = r24
                                                      r0.extend(SymbolNode)
                                                    else
                                                      if has_terminal?("\\xi", false, index)
                                                        r25 = instantiate_node(SyntaxNode,input, index...(index + 3))
                                                        @index += 3
                                                      else
                                                        terminal_parse_failure("\\xi")
                                                        r25 = nil
                                                      end
                                                      if r25
                                                        r0 = r25
                                                        r0.extend(SymbolNode)
                                                      else
                                                        if has_terminal?("\\pi", false, index)
                                                          r26 = instantiate_node(SyntaxNode,input, index...(index + 3))
                                                          @index += 3
                                                        else
                                                          terminal_parse_failure("\\pi")
                                                          r26 = nil
                                                        end
                                                        if r26
                                                          r0 = r26
                                                          r0.extend(SymbolNode)
                                                        else
                                                          if has_terminal?("\\rho", false, index)
                                                            r27 = instantiate_node(SyntaxNode,input, index...(index + 4))
                                                            @index += 4
                                                          else
                                                            terminal_parse_failure("\\rho")
                                                            r27 = nil
                                                          end
                                                          if r27
                                                            r0 = r27
                                                            r0.extend(SymbolNode)
                                                          else
                                                            if has_terminal?("\\varsigma", false, index)
                                                              r28 = instantiate_node(SyntaxNode,input, index...(index + 9))
                                                              @index += 9
                                                            else
                                                              terminal_parse_failure("\\varsigma")
                                                              r28 = nil
                                                            end
                                                            if r28
                                                              r0 = r28
                                                              r0.extend(SymbolNode)
                                                            else
                                                              if has_terminal?("\\sigma", false, index)
                                                                r29 = instantiate_node(SyntaxNode,input, index...(index + 6))
                                                                @index += 6
                                                              else
                                                                terminal_parse_failure("\\sigma")
                                                                r29 = nil
                                                              end
                                                              if r29
                                                                r0 = r29
                                                                r0.extend(SymbolNode)
                                                              else
                                                                if has_terminal?("\\tau", false, index)
                                                                  r30 = instantiate_node(SyntaxNode,input, index...(index + 4))
                                                                  @index += 4
                                                                else
                                                                  terminal_parse_failure("\\tau")
                                                                  r30 = nil
                                                                end
                                                                if r30
                                                                  r0 = r30
                                                                  r0.extend(SymbolNode)
                                                                else
                                                                  if has_terminal?("\\upsilon", false, index)
                                                                    r31 = instantiate_node(SyntaxNode,input, index...(index + 8))
                                                                    @index += 8
                                                                  else
                                                                    terminal_parse_failure("\\upsilon")
                                                                    r31 = nil
                                                                  end
                                                                  if r31
                                                                    r0 = r31
                                                                    r0.extend(SymbolNode)
                                                                  else
                                                                    if has_terminal?("\\phi", false, index)
                                                                      r32 = instantiate_node(SyntaxNode,input, index...(index + 4))
                                                                      @index += 4
                                                                    else
                                                                      terminal_parse_failure("\\phi")
                                                                      r32 = nil
                                                                    end
                                                                    if r32
                                                                      r0 = r32
                                                                      r0.extend(SymbolNode)
                                                                    else
                                                                      if has_terminal?("\\chi", false, index)
                                                                        r33 = instantiate_node(SyntaxNode,input, index...(index + 4))
                                                                        @index += 4
                                                                      else
                                                                        terminal_parse_failure("\\chi")
                                                                        r33 = nil
                                                                      end
                                                                      if r33
                                                                        r0 = r33
                                                                        r0.extend(SymbolNode)
                                                                      else
                                                                        if has_terminal?("\\psi", false, index)
                                                                          r34 = instantiate_node(SyntaxNode,input, index...(index + 4))
                                                                          @index += 4
                                                                        else
                                                                          terminal_parse_failure("\\psi")
                                                                          r34 = nil
                                                                        end
                                                                        if r34
                                                                          r0 = r34
                                                                          r0.extend(SymbolNode)
                                                                        else
                                                                          if has_terminal?("\\omega", false, index)
                                                                            r35 = instantiate_node(SyntaxNode,input, index...(index + 6))
                                                                            @index += 6
                                                                          else
                                                                            terminal_parse_failure("\\omega")
                                                                            r35 = nil
                                                                          end
                                                                          if r35
                                                                            r0 = r35
                                                                            r0.extend(SymbolNode)
                                                                          else
                                                                            if has_terminal?("\\rightarrow", false, index)
                                                                              r36 = instantiate_node(SyntaxNode,input, index...(index + 11))
                                                                              @index += 11
                                                                            else
                                                                              terminal_parse_failure("\\rightarrow")
                                                                              r36 = nil
                                                                            end
                                                                            if r36
                                                                              r0 = r36
                                                                              r0.extend(SymbolNode)
                                                                            else
                                                                              @index = i0
                                                                              r0 = nil
                                                                            end
                                                                          end
                                                                        end
                                                                      end
                                                                    end
                                                                  end
                                                                end
                                                              end
                                                            end
                                                          end
                                                        end
                                                      end
                                                    end
                                                  end
                                                end
                                              end
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end

      node_cache[:math_symbol][start_index] = r0

      r0
    end

  end

  class SymbolParser < Treetop::Runtime::CompiledParser
    include Symbol
  end

end