# Autogenerated from a Treetop grammar. Edits may be lost.


require "hemingway/override/override_nodes"

module Hemingway
  module Override
    include Treetop::Runtime

    def root
      @root ||= :override
    end

    def _nt_override
      start_index = index
      if node_cache[:override].has_key?(index)
        cached = node_cache[:override][index]
        if cached
          cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
          @index = cached.interval.end
        end
        return cached
      end

      i0 = index
      if has_terminal?("---", false, index)
        r1 = instantiate_node(MDashNode,input, index...(index + 3))
        @index += 3
      else
        terminal_parse_failure("---")
        r1 = nil
      end
      if r1
        r0 = r1
      else
        if has_terminal?("``", false, index)
          r2 = instantiate_node(LeftDoubleQuoteNode,input, index...(index + 2))
          @index += 2
        else
          terminal_parse_failure("``")
          r2 = nil
        end
        if r2
          r0 = r2
        else
          if has_terminal?("''", false, index)
            r3 = instantiate_node(RightDoubleQuoteNode,input, index...(index + 2))
            @index += 2
          else
            terminal_parse_failure("''")
            r3 = nil
          end
          if r3
            r0 = r3
          else
            if has_terminal?("`", false, index)
              r4 = instantiate_node(LeftSingleQuoteNode,input, index...(index + 1))
              @index += 1
            else
              terminal_parse_failure("`")
              r4 = nil
            end
            if r4
              r0 = r4
            else
              if has_terminal?("'", false, index)
                r5 = instantiate_node(RightSingleQuoteNode,input, index...(index + 1))
                @index += 1
              else
                terminal_parse_failure("'")
                r5 = nil
              end
              if r5
                r0 = r5
              else
                @index = i0
                r0 = nil
              end
            end
          end
        end
      end

      node_cache[:override][start_index] = r0

      r0
    end

  end

  class OverrideParser < Treetop::Runtime::CompiledParser
    include Override
  end

end